<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="Cityzen" failures="2" tests="2" name="Test(failed)(failed)" time="0.002" errors="0" timestamp="2024-06-10T18:15:51 EDT">
  <testcase classname="testngproject.FailedTestA" name="test2" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngproject.FailedTestA.test2(FailedTestA.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at testngproject.FailedTest.runFailedTests(FailedTest.java:21)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testngproject.FailedTestB" name="test4" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testngproject.FailedTestB.test4(FailedTestB.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at testngproject.FailedTest.runFailedTests(FailedTest.java:21)
... Removed 52 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="testngproject.FailedTestB" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="testngproject.FailedTestA" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test(failed)(failed) -->
